language: node_js
node_js:
  - 12

install: npm ci
script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: static
  on:
    branch: master
